name: 'Test File Suffix Inspector'
description: 'Scans test files in src/test directories to ensure naming conventions, reporting any files missing specified suffixes.'
inputs:
  suffixes:
    description: 'List of suffixes that test files should have, separated by commas (e.g., UnitTest,IntegrationTest).'
    required: true
    default: 'UnitTests,IntegrationTests'
  include_directories:
    description: 'List of directories to include in the pattern check, separated by commas. Defining this input limits scanning to these directories only.'
    required: false
    default: 'src/test/'
  excludes:
    description: 'List of glob patterns to exclude from controls, separated by commas (e.g., HelperUtils,Constants).'
    required: false
    default: ''
  case_sensitive:
    description: 'Determines if the filename check should be case-sensitive.'
    required: false
    default: 'true'
  contains:
    description: 'Switch logic from suffix (end of filename) to contains (any part of filename). Set to true to enable contains logic.'
    required: false
    default: 'false'
  report_format:
    description: 'Specifies the format of the output report. Options: console, csv, and json.'
    required: false
    default: 'console'
  verbose_logging:
    description: 'Enable verbose logging to provide detailed output during the action’s execution, aiding in troubleshooting and setup.'
    required: false
    default: 'false'
  fail_on_violation:
    description: 'Set to true to fail the action if any convention violations are detected. Set to false to continue without failure.'
    required: false
    default: 'false'
outputs:
  violation_count:
    description: 'Count of test files that do not comply with the specified suffix conventions.'
    value: ${{ steps.scan-test-files.outputs.violation_count }}
  report_path:
    description: 'Path to the generated report file.'
    value: ${{ steps.scan-test-files.outputs.report_path }}
runs:
  using: 'composite'
  steps:
    - name: Scan test files for suffix conventions
      id: scan-test-files
      env:
        INPUT_SUFFIXES: ${{ inputs.suffixes }}
        INPUT_INCLUDE_DIRECTORIES: ${{ inputs.include_directories }}
        INPUT_EXCLUDES: ${{ inputs.excludes }}
        INPUT_CASE_SENSITIVE: ${{ inputs.case_sensitive }}
        INPUT_CONTAINS: ${{ inputs.contains }}
        INPUT_REPORT_FORMAT: ${{ inputs.report_format }}
        INPUT_VERBOSE_LOGGING: ${{ inputs.verbose_logging }}
        INPUT_FAIL_ON_VIOLATION: ${{ inputs.fail_on_violation }}
      run: |
        python3 ${{ github.action_path }}/src/file_suffix_inspector.py
      shell: bash
