name: 'Test File Suffix Inspector'
description: 'Scans test files in src/test directories to ensure naming conventions, reporting any files missing specified suffixes.'
inputs:
  suffixes:
    description: 'List of suffixes that test files should have, separated by commas (e.g., UnitTest,IntegrationTest).'
    required: true
    default: 'UnitTests,IntegrationTests'
  include_directories:
    description: 'List of directories to include in the pattern check, separated by commas. Defining this input limits scanning to these directories only.'
    required: false
    default: 'src/test/'
  exclude_directories:
    description: 'List of project root directory names to exclude in the pattern check, separated by commas. Defining this input limits scanning to these directories only.'
    required: false
    default: 'dist,node_modules,coverage,target,.idea,.github,.git'
  exclude_files:
    description: 'List of filenames to exclude from suffix checks, separated by commas (e.g., HelperUtils,Constants).'
    required: false
    default: ''
  case_sensitivity:
    description: 'Determines if the filename check should be case-sensitive.'
    required: false
    default: 'true'
  logic:
    description: 'Switch logic from suffix (end of filename) to contains (any part of filename). Set to false to enable contains logic.'
    required: false
    default: 'true'
  report_format:
    description: 'Specifies the format of the output report. Options: console, csv, and json.'
    required: false
    default: 'console'
  verbose_logging:
    description: 'Enable verbose logging to provide detailed output during the action’s execution, aiding in troubleshooting and setup.'
    required: false
    default: 'false'
  fail_on_violations:
    description: 'Set to true to fail the action if any convention violations are detected. Set to false to continue without failure.'
    required: false
    default: 'false'
outputs:
  conventions_violations:
    description: 'Count of test files that do not comply with the specified suffix conventions.'
    value: ${{ steps.scan-test-files.outputs.conventions_violations }}
  report_path:
    description: 'Path to the generated report file.'
    value: ${{ steps.scan-test-files.outputs.report_path }}
runs:
  using: 'composite'
  steps:
    - name: Scan test files for suffix conventions
      id: scan-test-files
      env:
        INPUT_SUFFIXES: ${{ inputs.suffixes }}
        INPUT_INCLUDE_DIRECTORIES: ${{ inputs.include_directories }}
        INPUT_EXCLUDE_DIRECTORIES: ${{ inputs.exclude_directories }}
        INPUT_EXCLUDE_FILES: ${{ inputs.exclude_files }}
        INPUT_CASE_SENSITIVITY: ${{ inputs.case_sensitivity }}
        INPUT_LOGIC: ${{ inputs.logic }}
        INPUT_REPORT_FORMAT: ${{ inputs.report_format }}
        INPUT_VERBOSE_LOGGING: ${{ inputs.verbose_logging }}
        INPUT_FAIL_ON_VIOLATIONS: ${{ inputs.fail_on_violations }}
      run: |
        python3 ${{ github.action_path }}/src/file_suffix_inspector.py
      shell: bash
