name: Run Unit Tests

on:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.5
      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Execute unit tests
        run: |
          pytest ./tests
